# Data Cleaning

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

Read both .csv files for cleaning
* Ames Real Estate Data = data
* Amex_HousePrice = house

In [2]:
data = pd.read_csv("Ames Real Estate Data.csv", index_col=0)
house = pd.read_csv('Ames_HousePrice.csv', index_col=0)

C:\Users\David Jhang\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (36,40,81,87) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


Show max columns so we can see everything

In [46]:
#set columns
pd.get_option("display.max_columns") #this will display what the current setting is
pd.set_option("display.max_columns",None)

#set rows
pd.set_option("display.max_rows",None)

Start with house since that will hold the main SalePrice

In [31]:
house.shape

(2580, 81)

In [29]:
house.head()

PID  GrLivArea  SalePrice  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition
1  909176150        856     126000          30       RL          NaN     7890   Pave   NaN      Reg         Lvl    AllPub    Corner       Gtl        SWISU       Norm       Norm     1Fam     1Story            6            6       1939          1950     Gable  CompShg     Wd Sdng     Wd Sdng       None         0.0        TA        TA     CBlock       TA       TA           No          Rec       238.0          Unf         0.0      618.0        856.0    GasA        TA          Y      SBrkr       856         0             0           1.0           0.0         1         0             2             1          TA             4        Typ           1          Gd     Detchd       1939.0          Unf         2.0       399.0         TA         TA          Y           0            0              0          0          166         0    NaN   NaN         NaN        0       3    2010      WD         Normal
2  905476230       1049     139500         120       RL         42.0     4235   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl      Edwards       Norm       Norm   TwnhsE     1Story            5            5       1984          1984     Gable  CompShg     HdBoard     HdBoard    BrkFace       149.0        Gd        TA     CBlock       Gd       TA           Mn          GLQ       552.0          ALQ       393.0      104.0       1049.0    GasA        TA          Y      SBrkr      1049         0             0           1.0           0.0         2         0             2             1          Gd             5        Typ           0         NaN     Attchd       1984.0          Fin         1.0       266.0         TA         TA          Y           0          105              0          0            0         0    NaN   NaN         NaN        0       2    2009      WD         Normal
3  911128020       1001     124900          30  C (all)         60.0     6060   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl       IDOTRR       Norm       Norm     1Fam     1Story            5            9       1930          2007       Hip  CompShg     MetalSd     MetalSd       None         0.0        Gd        TA     BrkTil       TA       TA           No          ALQ       737.0          Unf         0.0      100.0        837.0    GasA        Ex          Y      SBrkr      1001         0             0           0.0           0.0         1         0             2             1          Gd             5        Typ           0         NaN     Detchd       1930.0          Unf         1.0       216.0         TA         Po          N         154            0             42         86            0         0    NaN   NaN         NaN        0      11    2007      WD         Normal
4  535377150       1039     114000          70       RL         80.0     8146   Pave   NaN      Reg         Lvl    AllPub    Corner       Gtl      OldTown       Norm       Norm     1Fam     2Story            4            8       1900          2003     Gable  CompShg     MetalSd     MetalSd       None         0.0        Gd        Gd     BrkTil       Fa       TA           No          Unf         0.0 

- house DF has the SalePrice column
- We need to use SalePrice as the Y (dependent variable)
- Will explore and seperate this column out

Checking for NAs

In [35]:
house.SalePrice.isnull().sum() # 0 NAs, good indication

0

Let's create a subset for the SalePrice
- Y_saleprice
- let's exam it closer



In [40]:
Y_saleprice = house.SalePrice
print("Mean:       ", Y_saleprice.mean())
print("Standard deviation:", Y_saleprice.std())
print("Minimum:    ", Y_saleprice.min())
print("Maximum:    ", Y_saleprice.max())

Mean:        178059.62325581396
Standard deviation: 75031.08937358031
Minimum:     12789
Maximum:     755000


Let's check for NAs for the whole house DF

In [48]:
house.shape #2580 rows and 81 columns

(2580, 81)

* PoolQC = Pool quality (Pool Area is also another column)
* MiscFeature =  Miscellaneous feature not covered in other categories (they have Misc Value)
* Alley = Type of alley access (no other Alley column)
* Fence = Fence quality (no other Fence column)
* FireplaceQu = Fireplace quality (note they have # of fireplaces as well)
* LotFrontage = Linear feet of street connected to property (width of the lot in the front)

In [47]:
house.isnull().sum().sort_values(ascending=False) #some of these columns have a high % of NAs

PoolQC           2571
MiscFeature      2483
Alley            2412
Fence            2055
FireplaceQu      1241
LotFrontage       462
GarageQual        129
GarageYrBlt       129
GarageFinish      129
GarageCond        129
GarageType        127
BsmtExposure       71
BsmtFinType2       70
BsmtQual           69
BsmtCond           69
BsmtFinType1       69
MasVnrType         14
MasVnrArea         14
BsmtFullBath        2
BsmtHalfBath        2
Electrical          1
BsmtUnfSF           1
BsmtFinSF2          1
BsmtFinSF1          1
TotalBsmtSF         1
GarageCars          1
GarageArea          1
LotConfig           0
RoofMatl            0
Exterior2nd         0
GrLivArea           0
SalePrice           0
MSSubClass          0
MSZoning            0
LotArea             0
Street              0
LotShape            0
LandContour         0
Exterior1st         0
RoofStyle           0
Neighborhood        0
YearRemodAdd        0
YearBuilt           0
OverallCond         0
OverallQual         0
Utilities 

In [57]:
house['PoolQC'].unique() #potential fill-in for "none" for poolQC

array([nan, 'Ex', 'Gd', 'Fa', 'TA'], dtype=object)

In [59]:
house['MiscFeature'].unique() #potentially none for this as well

array([nan, 'Shed', 'Othr', 'Gar2', 'TenC'], dtype=object)

In [60]:
house['Alley'].unique() #does this mean NO Alley?

array([nan, 'Pave', 'Grvl'], dtype=object)

In [61]:
house['Fence'].unique() #does this mean NO fence?

array([nan, 'GdWo', 'MnPrv', 'GdPrv', 'MnWw'], dtype=object)

In [62]:
house['FireplaceQu'].unique() #need to figure this one out later

array(['Gd', nan, 'Ex', 'TA', 'Fa', 'Po'], dtype=object)

In [63]:
house['LotFrontage'].unique() # is it possible to have NO LOT FRONTAGE?

array([ nan,  42.,  60.,  80.,  70.,  64.,  53.,  74.,  35.,  48.,  63.,
        62.,  50.,  68.,  45.,  65.,  21.,  58.,  73., 105., 100.,  88.,
        52.,  71.,  76., 101.,  59.,  56.,  32.,  78., 110.,  96.,  61.,
       108.,  75., 106.,  84.,  67., 168.,  49., 140.,  66.,  92., 125.,
        85.,  72.,  24.,  79., 130.,  77.,  94.,  91.,  90.,  82., 149.,
        43.,  69.,  95.,  40.,  51.,  47.,  89.,  22.,  38., 118.,  87.,
        86.,  54.,  39.,  41.,  30., 128.,  46.,  99.,  44.,  36., 107.,
       104.,  34.,  57.,  81., 113., 120., 115., 150., 116.,  37., 129.,
        98., 121., 195., 160.,  83., 102.,  93.,  55., 124., 131.,  33.,
       137., 111., 134.,  26., 103., 313.,  28., 114., 174., 141., 117.,
        25., 112., 155., 109., 152., 153., 122.,  31., 126.,  97., 200.,
       136., 119., 135., 144., 123., 138.])